### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [iambumblehead/caramelcookie#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by iambumblehead** [comment]
@geopic a PR would be accepted, however, I doubt many will use this cookie package :)

**Comment by geopic** [comment]
I'll get started on one now, it's worth having one at least :smiley:
